### ISSUE TITLE
Improve the environment modules strategy in khiops_env (linux only)

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#396]
#### Description
On fedora distro, if mpiexec is not found, khiops_env load the environment module of openmpi.
We don't deal with the case where mpich is loaded before khiops_env is started. In this case, we need to unload the inappropriate module and load openmpi.

### Context
- Linux

**Comment by bruno-at-orange** [comment]
fixed with e2b0b70c96c40dd6c13c184ace79d7ff858c2531 ?

**Comment by popescu-v** [comment]
> fixed with [e2b0b70](https://github.com/KhiopsML/khiops/commit/e2b0b70c96c40dd6c13c184ace79d7ff858c2531) ?

This commit fixes the current issue, but does not fix issue https://github.com/KhiopsML/khiops/issues/495. However, the fix proposed by @bruno-at-orange in comment https://github.com/KhiopsML/khiops/issues/495#issuecomment-2566312946 would do IMHO.
